package hibenete;
// Generated 30/10/2019 21:46:55 by Hibernate Tools 4.3.1



/**
 * Livro generated by hbm2java
 */
public class Livro  implements java.io.Serializable {


     private LivroId id;
     private String titulo;
     private Float preco;
     private Integer estoque;

    public Livro() {
    }

	
    public Livro(LivroId id, String titulo) {
        this.id = id;
        this.titulo = titulo;
    }
    public Livro(LivroId id, String titulo, Float preco, Integer estoque) {
       this.id = id;
       this.titulo = titulo;
       this.preco = preco;
       this.estoque = estoque;
    }
   
    public LivroId getId() {
        return this.id;
    }
    
    public void setId(LivroId id) {
        this.id = id;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Float getPreco() {
        return this.preco;
    }
    
    public void setPreco(Float preco) {
        this.preco = preco;
    }
    public Integer getEstoque() {
        return this.estoque;
    }
    
    public void setEstoque(Integer estoque) {
        this.estoque = estoque;
    }




}


