package hibenete;
// Generated 30/10/2019 21:46:55 by Hibernate Tools 4.3.1



/**
 * LivroId generated by hbm2java
 */
public class LivroId  implements java.io.Serializable {


     private int idlivro;
     private int idgenero;
     private int ideditora;

    public LivroId() {
    }

    public LivroId(int idlivro, int idgenero, int ideditora) {
       this.idlivro = idlivro;
       this.idgenero = idgenero;
       this.ideditora = ideditora;
    }
   
    public int getIdlivro() {
        return this.idlivro;
    }
    
    public void setIdlivro(int idlivro) {
        this.idlivro = idlivro;
    }
    public int getIdgenero() {
        return this.idgenero;
    }
    
    public void setIdgenero(int idgenero) {
        this.idgenero = idgenero;
    }
    public int getIdeditora() {
        return this.ideditora;
    }
    
    public void setIdeditora(int ideditora) {
        this.ideditora = ideditora;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LivroId) ) return false;
		 LivroId castOther = ( LivroId ) other; 
         
		 return (this.getIdlivro()==castOther.getIdlivro())
 && (this.getIdgenero()==castOther.getIdgenero())
 && (this.getIdeditora()==castOther.getIdeditora());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdlivro();
         result = 37 * result + this.getIdgenero();
         result = 37 * result + this.getIdeditora();
         return result;
   }   


}


